// TEMPORARY DATA

export const role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "ET001",
    name: "Abebe Kebede",
    email: "abebe.kebede@school.et",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251911223344",
    subjects: ["Math", "Geometry"],
    classes: ["9A", "10B", "11C"],
    address: "Piassa, Addis Ababa, Ethiopia",
  },
  {
    id: 2,
    teacherId: "ET002",
    name: "Tigist Alemu",
    email: "tigist.alemu@school.et",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251922334455",
    subjects: ["Physics", "Chemistry"],
    classes: ["11A", "10C", "9B"],
    address: "4 Kilo, Addis Ababa, Ethiopia",
  },
  {
    id: 3,
    teacherId: "ET003",
    name: "Mulugeta Teshome",
    email: "mulugeta.teshome@school.et",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251933445566",
    subjects: ["Biology"],
    classes: ["12A", "11C", "10B"],
    address: "Arat Kilo, Addis Ababa, Ethiopia",
  },
  {
    id: 4,
    teacherId: "ET004",
    name: "Hirut Bekele",
    email: "hirut.bekele@school.et",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251944556677",
    subjects: ["History"],
    classes: ["8A", "9C", "10D"],
    address: "Adama, Oromia, Ethiopia",
  },
  {
    id: 5,
    teacherId: "ET005",
    name: "Meskerem Yohannes",
    email: "meskerem.yohannes@school.et",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251955667788",
    subjects: ["Music", "History"],
    classes: ["7A", "8C", "9B"],
    address: "Gondar, Amhara, Ethiopia",
  },
  {
    id: 6,
    teacherId: "ET006",
    name: "Samuel Getachew",
    email: "samuel.getachew@school.et",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251966778899",
    subjects: ["Physics"],
    classes: ["11B", "10D", "12A"],
    address: "Hawassa, SNNPR, Ethiopia",
  },
  {
    id: 7,
    teacherId: "ET007",
    name: "Betelhem Mekonnen",
    email: "betelhem.mekonnen@school.et",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251977889900",
    subjects: ["English", "Amharic"],
    classes: ["7B", "8A", "9C"],
    address: "Bahir Dar, Amhara, Ethiopia",
  },
  {
    id: 8,
    teacherId: "ET008",
    name: "Yonas Gebremariam",
    email: "yonas.gebremariam@school.et",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251988990011",
    subjects: ["Math", "Geometry"],
    classes: ["9A", "10C", "11B"],
    address: "Mekelle, Tigray, Ethiopia",
  },
  {
    id: 9,
    teacherId: "ET009",
    name: "Selamawit Desta",
    email: "selamawit.desta@school.et",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251999001122",
    subjects: ["Literature", "English"],
    classes: ["8C", "9A", "10B"],
    address: "Dire Dawa, Ethiopia",
  },
  {
    id: 10,
    teacherId: "ET010",
    name: "Tesfaye Hailemariam",
    email: "tesfaye.hailemariam@school.et",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251911223355",
    subjects: ["Biology"],
    classes: ["11A", "12B", "9C"],
    address: "Jimma, Oromia, Ethiopia",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "ST001",
    name: "Mikiyas Abebe",
    email: "mikiyas.abebe@student.et",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251911112233",
    grade: 9,
    class: "9A",
    address: "Piassa, Addis Ababa, Ethiopia",
  },
  {
    id: 2,
    studentId: "ST002",
    name: "Lidya Tadesse",
    email: "lidya.tadesse@student.et",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251922223344",
    grade: 10,
    class: "10B",
    address: "Arat Kilo, Addis Ababa, Ethiopia",
  },
  {
    id: 3,
    studentId: "ST003",
    name: "Nahom Getachew",
    email: "nahom.getachew@student.et",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251933334455",
    grade: 11,
    class: "11A",
    address: "Bole, Addis Ababa, Ethiopia",
  },
  {
    id: 4,
    studentId: "ST004",
    name: "Saron Bekele",
    email: "saron.bekele@student.et",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251944445566",
    grade: 8,
    class: "8C",
    address: "Adama, Oromia, Ethiopia",
  },
  {
    id: 5,
    studentId: "ST005",
    name: "Brook Haile",
    email: "brook.haile@student.et",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251955556677",
    grade: 12,
    class: "12B",
    address: "Gondar, Amhara, Ethiopia",
  },
  {
    id: 6,
    studentId: "ST006",
    name: "Hanna Girma",
    email: "hanna.girma@student.et",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251966667788",
    grade: 9,
    class: "9C",
    address: "Hawassa, SNNPR, Ethiopia",
  },
  {
    id: 7,
    studentId: "ST007",
    name: "Yonatan Alemayehu",
    email: "yonatan.alemayehu@student.et",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251977778899",
    grade: 10,
    class: "10A",
    address: "Bahir Dar, Amhara, Ethiopia",
  },
  {
    id: 8,
    studentId: "ST008",
    name: "Meron Desta",
    email: "meron.desta@student.et",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251988889900",
    grade: 11,
    class: "11C",
    address: "Mekelle, Tigray, Ethiopia",
  },
  {
    id: 9,
    studentId: "ST009",
    name: "Bereket Solomon",
    email: "bereket.solomon@student.et",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251999990011",
    grade: 12,
    class: "12A",
    address: "Dire Dawa, Ethiopia",
  },
  {
    id: 10,
    studentId: "ST010",
    name: "Rahel Tesfaye",
    email: "rahel.tesfaye@student.et",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "+251911112244",
    grade: 8,
    class: "8A",
    address: "Jimma, Oromia, Ethiopia",
  },
];


export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john.doe@example.com",
    phone: "555-1001",
    address: "123 Maple St, Springfield, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane.doe@example.com",
    phone: "555-1002",
    address: "456 Oak Ave, Springfield, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike.geller@example.com",
    phone: "555-1003",
    address: "789 Pine Rd, Springfield, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "jay.french@example.com",
    phone: "555-1004",
    address: "321 Birch Blvd, Springfield, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "jane.smith@example.com",
    phone: "555-1005",
    address: "654 Cedar Ln, Springfield, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "anna.santiago@example.com",
    phone: "555-1006",
    address: "987 Willow Dr, Springfield, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "allen.black@example.com",
    phone: "555-1007",
    address: "246 Elm Ct, Springfield, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "ophelia.castro@example.com",
    phone: "555-1008",
    address: "135 Cherry St, Springfield, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "derek.briggs@example.com",
    phone: "555-1009",
    address: "579 Poplar Rd, Springfield, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "john.glover@example.com",
    phone: "555-1010",
    address: "864 Aspen Way, Springfield, USA",
  },
];



export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
const today = new Date();
const year = today.getFullYear();   // 2025
const month = today.getMonth();     // 7 = August
const day = today.getDate();        // 20

export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(year, month, day, 8, 0),
    end: new Date(year, month, day, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(year, month, day, 9, 0),
    end: new Date(year, month, day, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(year, month, day, 10, 0),
    end: new Date(year, month, day, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(year, month, day, 11, 0),
    end: new Date(year, month, day, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(year, month, day, 13, 0),
    end: new Date(year, month, day, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(year, month, day, 14, 0),
    end: new Date(year, month, day, 14, 45),
  },

  // Next day
  {
    title: "English",
    allDay: false,
    start: new Date(year, month, day + 1, 9, 0),
    end: new Date(year, month, day + 1, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(year, month, day + 1, 10, 0),
    end: new Date(year, month, day + 1, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(year, month, day + 1, 11, 0),
    end: new Date(year, month, day + 1, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(year, month, day + 1, 14, 0),
    end: new Date(year, month, day + 1, 14, 45),
  },

  // +2 days
  {
    title: "Math",
    allDay: false,
    start: new Date(year, month, day + 2, 8, 0),
    end: new Date(year, month, day + 2, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(year, month, day + 2, 10, 0),
    end: new Date(year, month, day + 2, 10, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(year, month, day + 2, 13, 0),
    end: new Date(year, month, day + 2, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(year, month, day + 2, 14, 0),
    end: new Date(year, month, day + 2, 14, 45),
  },

  // +3 days
  {
    title: "English",
    allDay: false,
    start: new Date(year, month, day + 3, 9, 0),
    end: new Date(year, month, day + 3, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(year, month, day + 3, 10, 0),
    end: new Date(year, month, day + 3, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(year, month, day + 3, 11, 0),
    end: new Date(year, month, day + 3, 11, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(year, month, day + 3, 14, 0),
    end: new Date(year, month, day + 3, 14, 45),
  },

  // +4 days
  {
    title: "Math",
    allDay: false,
    start: new Date(year, month, day + 4, 8, 0),
    end: new Date(year, month, day + 4, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(year, month, day + 4, 9, 0),
    end: new Date(year, month, day + 4, 9, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(year, month, day + 4, 11, 0),
    end: new Date(year, month, day + 4, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(year, month, day + 4, 13, 0),
    end: new Date(year, month, day + 4, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(year, month, day + 4, 14, 0),
    end: new Date(year, month, day + 4, 14, 45),
  },
];
